$(document).ready(function() {
    $('#displayTable').DataTable( {
        /*"scrollY":        "200px",
        "scrollCollapse": true,
        "paging":         false*/
    	responsive: true,
        "pageLength": 10
    } );
    $('#displayTable1').DataTable( {
        /*"scrollY":        "200px",
        "scrollCollapse": true,
        "paging":         false*/
    	responsive: true,
        "pageLength": 10
    } );
    $('#displayTable2').DataTable( {
        /*"scrollY":        "200px",
        "scrollCollapse": true,
        "paging":         false*/
    	responsive: true,
        "pageLength": 10
    } );
} );